jobs:
  pyinstaller-build:
    runs-on: <windows-latest>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.9'
          spec: '4imask_anonymizer.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: '4imask_anonymizer'
          options: --name "4imask_anonymizer", --windowed, 
